server:
    port: 8080
    context-path: /heroes-service/

spring: 
    main:
        banner-mode: "off"     
          
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 3600000

logging: 
    level: 
        org.springframework: INFO
        com.uwefuchs.demo.heroestutorial.service: DEBUG
